package: api

generate:
  models: true
  chi-server: true

output: internal/generated/api.gen.go

output-options:
  include-operation-ids:
    - createTrip
    - getTrip
    - finishTrip
    - health
    - ready